### ISSUE TITLE
Can you please mention - from where we can fetch Reddit Dataset 

### ISSUE THREAD

**Issue by harshgeek4coder** [cjunwon/Reddit-Social-Network-Analysis#1]
Can you please mention in the README - how to get the reddit dataset used in this project ?

Thanks,
Harsh

**Comment by cjunwon** [comment]
Thank you for reaching out! The following code
```
from torch_geometric.datasets import Reddit

path = 'Datasets'

dataset = Reddit(path, transform=None)
```
should allow you to access the data from PyTorch Geometric.

The README will be updated soon.
